baseURL = "https://albertogalvez.com/"
title = "AG"
paginate = 5
theme = "PaperMod"
hideFooter = true
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = ["posts", "papermod"]
googleAnalytics =  "G-6EH7910J7K"

[minify]
disableXML = true

[languages]
[languages.en]
languageName = "English"
weight = 1
[languages.en.taxonomies]
category = "categories"
tag = "tags"
series = "series"
[languages.en.menu]

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
env = "production"
description = ""
author = "Alberto"
defaultTheme = "auto"
ShowShareButtons = false
ShowReadingTime = false
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = false
ShowAllPagesInArchive = false
ShowPageNums = true
ShowToc = true
TocOpen = true
images = ["images/logo.png"]
[params.profileMode]
enabled = true
title = "Alberto Galvez"

[[params.socialIcons]]
name = "github"
title = "View Source on Github"
url = "https://github.com/agmalpartida"

[[params.socialIcons]]
name = "linkedin"
title = ""
url = "https://www.linkedin.com/in/agmalpartida/"
[params.editPost]
URL = "https://github.com/agmalpartida/brand/tree/published/content"
Text = "Suggest Changes"
appendFilePath = true
[params.assets]
disableHLJS = true
favicon = "img/favicon.png"
favicon16x16 = "img/favicon.png"
favicon32x32 = "img/favicon.png"
apple_touch_icon = "img/favicon.png"
safari_pinned_tab = "img/favicon.png"
# disableFingerprinting = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title"]

[markup]
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
noClasses = false
style = "monokai"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
